//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMMeCardSharingStateController : NSObject
{
}

+ (id)sharedInstance;
- (BOOL)wasSharingEverEnabled;
- (void)_syncPreferenceDidChange;
- (void)_incrementSharingVersion;
@property(nonatomic) BOOL imageForkedFromMeCard;
@property(nonatomic) BOOL nameForkedFromMeCard;
- (void)postNameFormatChangedNotification;
@property(nonatomic) unsigned long long nameFormat;
@property(nonatomic) unsigned long long sharingAudience;
@property(nonatomic) BOOL sharingEnabled;
- (void)_migrateMeCardDomains;
- (id)init;

@end

