//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMSharedUtilities/IMPreviewGenerator.h>

@interface IMMoviePreviewGenerator : IMPreviewGenerator
{
}

+ (id)_avAssetForURL:(id)arg1;
+ (Class)__AVAssetImageGeneratorClass;
+ (Class)__AVURLAssetClass;
+ (BOOL)isAutoloopAsset:(id)arg1;
+ (id)UTITypes;
+ (id)fetchUTITypes;

@end

