//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (IMKeyValueCollectionUserDefaultsStorage)
+ (id)dataWithMessageSummaryInfoDictionary:(id)arg1;
- (BOOL)isArchivable_im;
- (id)__im_engramStringRepresentation;
@end

