//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSFileManager.h>

@interface NSFileManager (IMSharedUtilities)
- (BOOL)__im_makeDirectoriesInPath:(id)arg1 mode:(unsigned int)arg2;
- (BOOL)__im_isPathOnMissingVolume:(id)arg1;
@end

