//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMSharedUtilities/IMFileTransfer.h>

@interface IMFileTransfer (SocialAppsCoreAdditions)
+ (BOOL)imShouldArchivePath:(id)arg1 depth:(unsigned long long)arg2;
+ (BOOL)doesLocalURLRequireArchiving:(id)arg1;
- (id)userVisibleLocalURL;
- (BOOL)isFileUserVisible;
@end

