//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMCore/IMPerson.h>

@interface IMPerson (SocialAppsCoreAdditions)
- (long long)queryStatusForIDSService:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)linkedPeople;
@end

