//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMCore/IMPluginPayload.h>

@interface IMPluginPayload (SocialAppsCoreAdditions)
- (id)businessPayloadDictionaryRepresentation;
- (id)businessMessageActionURL;
- (id)superFormatStringForFileTransfers:(id *)arg1;
@end

