//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (SOMetadata)
+ (id)metadataForServiceName:(id)arg1 dateCreated:(id)arg2 dateModified:(id)arg3 loginIMHandle:(id)arg4 participants:(id)arg5 roomName:(id)arg6 lastMessageID:(id)arg7;
@end

