//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMapTable.h>

@interface NSMapTable (SOTimerCenterAdditions)
- (void)removeTimer:(id)arg1 fromListener:(id)arg2;
- (void)addTimer:(id)arg1 toListener:(id)arg2;
@end

