//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableOrderedSet.h>

@interface NSMutableOrderedSet (SOTimerCenterAdditions)
- (void)removeTimer:(id)arg1;
- (void)addTimerAndSort:(id)arg1;
@end

