//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@interface NSMutableDictionary (SOSystemIdleMonitorAdditions)
- (id)timeoutIntervalsForListener:(id)arg1;
- (BOOL)listenerRegistered:(id)arg1 forTimeInterval:(id)arg2;
- (void)removeTimer:(id)arg1 fromGroup:(id)arg2;
- (void)addTimer:(id)arg1 toGroup:(id)arg2;
@end

