//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (SOSecureCoding)
+ (id)allowedSecureArchivingClasses_so;
+ (id)allowedMessagesSecureArchivingClasses_so;
+ (id)allowedAppKitSecureArchivingClasses_so;
@end

