//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSURL.h>

@interface NSURL (SocialAppsCoreAdditions)
- (BOOL)isLivePhotoAttachmentURL;
- (BOOL)isAnimatedEmojiAttachmentURL;
- (id)securityScopedURL;
- (id)sanitizeNoPrompt;
- (BOOL)isAudioMessageAttachmentURL;
- (BOOL)isMapAttachmentURL;
- (id)type;
@end

