//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSUserDefaults.h>

@interface NSUserDefaults (SocialAppsCoreAdditions)
+ (void)setNotifyAboutMessagesFromUnknownContacts:(BOOL)arg1;
+ (BOOL)notifyAboutMessagesFromUnknownContacts;
- (double)doubleForKey:(id)arg1 defaultValue:(double)arg2;
- (float)floatForKey:(id)arg1 defaultValue:(float)arg2;
- (long long)integerForKey:(id)arg1 defaultValue:(long long)arg2;
- (BOOL)boolForKey:(id)arg1 defaultValue:(BOOL)arg2;
@end

