//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMAddressBook : NSObject
{
}

+ (BOOL)addressBookEnabled;
+ (void)setAddressBookEnabled:(BOOL)arg1;
+ (id)abAddressBook;
+ (void)_watchLocaleChanges;
+ (void)_localeChanged:(id)arg1;

@end

