//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>

@class IMBalloonPluginDataSource;

@protocol IMBalloonPluginController <NSObject>
- (id)initWithDataSource:(IMBalloonPluginDataSource *)arg1 isFromMe:(BOOL)arg2;
@end

