//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface IMDirectlyObservableObject : NSObject
{
    NSArray *_observers;
}

//- (void).cxx_destruct;
@property(retain) NSArray *observers; // @synthesize observers=_observers;
- (void)informObserversOfNotification:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)_objectDidPostNotification:(id)arg1;
- (void)dealloc;

@end

