//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMCore/IMTranscriptChatItem.h>

#import <IMCore/IMChatTranscriptStatusItem-Protocol.h>

@class IMHandle, IMServiceImpl, NSAttributedString, NSDate, NSString;

@interface IMMessageStatusChatItem : IMTranscriptChatItem <IMChatTranscriptStatusItem>
{
    long long _statusType;
    NSDate *_time;
    long long _expireStatusType;
    NSDate *_timeAdded;
    NSDate *_timeStale;
    unsigned long long _count;
}

//- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long count; // @synthesize count=_count;
@property(readonly, nonatomic) long long expireStatusType; // @synthesize expireStatusType=_expireStatusType;
@property(readonly, nonatomic) NSDate *time; // @synthesize time=_time;
@property(readonly, nonatomic) long long statusType; // @synthesize statusType=_statusType;
- (id)_initWithItem:(id)arg1 statusType:(long long)arg2 time:(id)arg3 count:(unsigned long long)arg4 expireStatusType:(long long)arg5;
- (id)_initWithItem:(id)arg1 expireStatusType:(long long)arg2 count:(unsigned long long)arg3;
//if expireStatusType==3, show "Keep" button [ChatItemDOMProvider _parseMessageStatus:]
//if expireStatusType==2, show "Exipres in 2 minutes"
- (id)_initWithItem:(id)arg1 statusType:(long long)arg2 time:(id)arg3 count:(unsigned long long)arg4;
@property(readonly, nonatomic) long long messageStatusType; //from [SOMessageStatusCollectionViewItem stringForChatTranscriptItem:] and [SODefaultTranscriptTheme stringForMessageStatusType:statusDate:attributionType:] in SocialUI
//1: Delivered
//2: Read
//3: Played
//4: Kept
//5, 6, 8, 9, 12: not supported on macos
//7: Not Delivered
//10: attribution - must be IMMessageAttributionChatItem - then, according to [IMMessageAttributionChatItem attributionType]
//    - 6: Sent with Siri
//    - other: not supported on macos

@property(readonly, nonatomic) NSString *errorText;
@property(readonly, nonatomic, getter=isFromMe) BOOL fromMe;
- (void)_setTimeAdded:(id)arg1;
- (id)_timeAdded;
- (id)_timeStale;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) NSDate *dateOfStatus;
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic) IMHandle *handle;
//@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) BOOL isFromMe;
@property(readonly, nonatomic) IMServiceImpl *service;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSDate *transcriptDate;
@property(readonly, copy, nonatomic) NSAttributedString *transcriptText;
@property(readonly, nonatomic) BOOL wantsTail;

@end

