//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IMDaemonController;
@protocol IMRemoteDaemonProtocol;

@interface IMOneTimeCodeAccelerator : NSObject
{
    BOOL _requestedOneTimeCodeStatusForConnection;
    IMDaemonController<IMRemoteDaemonProtocol> *_daemon;
    id _updateBlock;
}

//- (void).cxx_destruct;
@property(nonatomic) BOOL requestedOneTimeCodeStatusForConnection; // @synthesize requestedOneTimeCodeStatusForConnection=_requestedOneTimeCodeStatusForConnection;
@property(copy, nonatomic) id updateBlock; // @synthesize updateBlock=_updateBlock;
@property(retain, nonatomic) IMDaemonController<IMRemoteDaemonProtocol> *daemon; // @synthesize daemon=_daemon;
- (void)daemonConnectionLost;
- (void)daemonControllerDidDisconnect;
- (void)daemonControllerDidConnect;
- (void)daemonControllerWillConnect;
- (void)_incomingCodeUpdateFromDaemon:(id)arg1;
- (void)setUpConnectionToDaemaon;
- (void)dealloc;
- (id)initWithDaemon:(id)arg1 andBlock:(id)arg2;
- (void)consumeCodeWithGuid:(id)arg1;
- (id)initWithBlockForUpdates:(id)arg1;

@end

