//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMCore/IMTranscriptChatItem.h>

@class IMHandle;

@interface IMParticipantChangeChatItem : IMTranscriptChatItem
{
    IMHandle *_sender;
    IMHandle *_otherHandle;
}

//- (void).cxx_destruct;

/*
 reference: [ChatItemDOMProvider _parseParticipantChangeChatItem:] in SocialUI
 
 pseudocode to display:
 
if changeType==0:
  # action = add/join
  if service==[IMServiceImpl iMessageService]:
    if sender != nil:
      message = "<sender> added <otherHandle> to the conversation"
    else
      message = "You added <otherHandle> to the conversation"
  else # not iMessage
    message = "<otherHandle> joined the conversation"
else if changeType==1:
  # action = remove/leave
  if service==[IMServiceImpl iMessageService]:
    if sender != nil:
      message = "<sender> removed <otherHandle> from the conversation"
    else
      message = "You removed <otherHandle> from the conversation"
  else
    message = "<otherHandle> left the conversation"
else: #unknown changeType
   error()
 
 */

@property(readonly, nonatomic) IMHandle *otherHandle; // @synthesize otherHandle=_otherHandle;
@property(readonly, nonatomic) IMHandle *sender; // @synthesize sender=_sender;
- (id)_initWithItem:(id)arg1 sender:(id)arg2 otherHandle:(id)arg3;
@property(readonly, nonatomic) long long changeType;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

