//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet, NSString;

@interface IMParentalControlsService : NSObject
{
    BOOL _disableService;
    BOOL _forceWhiteList;
    NSSet *_whitelist;
    NSString *_name;
}

//- (void).cxx_destruct;
@property(retain) NSString *name; // @synthesize name=_name;
@property(retain) NSSet *whitelist; // @synthesize whitelist=_whitelist;
@property BOOL forceWhiteList; // @synthesize forceWhiteList=_forceWhiteList;
@property BOOL disableService; // @synthesize disableService=_disableService;
- (void)dealloc;

@end

