//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>

@class IMBalloonPluginDataSource, NSString;

@protocol IMPluginChatItemProtocol <NSObject>
@property(readonly, nonatomic) BOOL isFromMe;
@property(readonly, retain, nonatomic) IMBalloonPluginDataSource *dataSource;
@property(readonly, retain, nonatomic) NSString *type;
@end

