//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMSharedUtilities/IMRecentItemsList.h>

@interface IMRecentItemsList (FetchUtilities)
- (void)loadRecentHandwritingsAndStickersWithThumbnailSize:(struct CGSize)arg1 completion:(id)arg2;
- (void)loadRecentHandwritingsWithThumbnailSize:(struct CGSize)arg1 completion:(id)arg2;
- (void)loadRecentStickers:(id)arg1;
@end

