//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, NSString;

@protocol INSpeakable <NSObject>
@property(readonly) NSArray *alternativeSpeakableMatches;
@property(readonly) NSString *vocabularyIdentifier;
@property(readonly) NSString *pronunciationHint;
@property(readonly) NSString *spokenPhrase;

@optional
@property(readonly) NSString *identifier;
@end

